# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'StayTuneApp' do
  # Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

  pod 'SwiftGen'
  pod 'KeychainAccess'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'IQKeyboardManager'

  # Pods for StayTuneApp
  pod 'SnapKit', '~> 5.0.0'
  target 'StayTuneAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StayTuneAppUITests' do
    # Pods for testing
  end

end
